// Major Indian cities with state
export const INDIAN_CITIES = [
    { city: "Mumbai", state: "Maharashtra", display: "Mumbai, Maharashtra" },
    { city: "Delhi", state: "Delhi", display: "Delhi, Delhi" },
    { city: "Bangalore", state: "Karnataka", display: "Bangalore, Karnataka" },
    { city: "Hyderabad", state: "Telangana", display: "Hyderabad, Telangana" },
    { city: "Ahmedabad", state: "Gujarat", display: "Ahmedabad, Gujarat" },
    { city: "Chennai", state: "Tamil Nadu", display: "Chennai, Tamil Nadu" },
    { city: "Kolkata", state: "West Bengal", display: "Kolkata, West Bengal" },
    { city: "Pune", state: "Maharashtra", display: "Pune, Maharashtra" },
    { city: "Jaipur", state: "Rajasthan", display: "Jaipur, Rajasthan" },
    { city: "Surat", state: "Gujarat", display: "Surat, Gujarat" },
    { city: "Lucknow", state: "Uttar Pradesh", display: "Lucknow, Uttar Pradesh" },
    { city: "Kanpur", state: "Uttar Pradesh", display: "Kanpur, Uttar Pradesh" },
    { city: "Nagpur", state: "Maharashtra", display: "Nagpur, Maharashtra" },
    { city: "Indore", state: "Madhya Pradesh", display: "Indore, Madhya Pradesh" },
    { city: "Thane", state: "Maharashtra", display: "Thane, Maharashtra" },
    { city: "Bhopal", state: "Madhya Pradesh", display: "Bhopal, Madhya Pradesh" },
    { city: "Visakhapatnam", state: "Andhra Pradesh", display: "Visakhapatnam, Andhra Pradesh" },
    { city: "Pimpri-Chinchwad", state: "Maharashtra", display: "Pimpri-Chinchwad, Maharashtra" },
    { city: "Patna", state: "Bihar", display: "Patna, Bihar" },
    { city: "Vadodara", state: "Gujarat", display: "Vadodara, Gujarat" },
    { city: "Ghaziabad", state: "Uttar Pradesh", display: "Ghaziabad, Uttar Pradesh" },
    { city: "Ludhiana", state: "Punjab", display: "Ludhiana, Punjab" },
    { city: "Agra", state: "Uttar Pradesh", display: "Agra, Uttar Pradesh" },
    { city: "Nashik", state: "Maharashtra", display: "Nashik, Maharashtra" },
    { city: "Ranchi", state: "Jharkhand", display: "Ranchi, Jharkhand" },
    { city: "Faridabad", state: "Haryana", display: "Faridabad, Haryana" },
    { city: "Meerut", state: "Uttar Pradesh", display: "Meerut, Uttar Pradesh" },
    { city: "Rajkot", state: "Gujarat", display: "Rajkot, Gujarat" },
    { city: "Kalyan-Dombivali", state: "Maharashtra", display: "Kalyan-Dombivali, Maharashtra" },
    { city: "Vasai-Virar", state: "Maharashtra", display: "Vasai-Virar, Maharashtra" },
    { city: "Varanasi", state: "Uttar Pradesh", display: "Varanasi, Uttar Pradesh" },
    { city: "Srinagar", state: "Jammu and Kashmir", display: "Srinagar, Jammu and Kashmir" },
    { city: "Aurangabad", state: "Maharashtra", display: "Aurangabad, Maharashtra" },
    { city: "Dhanbad", state: "Jharkhand", display: "Dhanbad, Jharkhand" },
    { city: "Amritsar", state: "Punjab", display: "Amritsar, Punjab" },
    { city: "Navi Mumbai", state: "Maharashtra", display: "Navi Mumbai, Maharashtra" },
    { city: "Allahabad", state: "Uttar Pradesh", display: "Allahabad, Uttar Pradesh" },
    { city: "Howrah", state: "West Bengal", display: "Howrah, West Bengal" },
    { city: "Gwalior", state: "Madhya Pradesh", display: "Gwalior, Madhya Pradesh" },
    { city: "Jabalpur", state: "Madhya Pradesh", display: "Jabalpur, Madhya Pradesh" },
    { city: "Coimbatore", state: "Tamil Nadu", display: "Coimbatore, Tamil Nadu" },
    { city: "Vijayawada", state: "Andhra Pradesh", display: "Vijayawada, Andhra Pradesh" },
    { city: "Jodhpur", state: "Rajasthan", display: "Jodhpur, Rajasthan" },
    { city: "Madurai", state: "Tamil Nadu", display: "Madurai, Tamil Nadu" },
    { city: "Raipur", state: "Chhattisgarh", display: "Raipur, Chhattisgarh" },
    { city: "Kota", state: "Rajasthan", display: "Kota, Rajasthan" },
    { city: "Chandigarh", state: "Chandigarh", display: "Chandigarh, Chandigarh" },
    { city: "Guwahati", state: "Assam", display: "Guwahati, Assam" },
    { city: "Solapur", state: "Maharashtra", display: "Solapur, Maharashtra" },
    { city: "Hubli-Dharwad", state: "Karnataka", display: "Hubli-Dharwad, Karnataka" },
    { city: "Mysore", state: "Karnataka", display: "Mysore, Karnataka" },
    { city: "Tiruchirappalli", state: "Tamil Nadu", display: "Tiruchirappalli, Tamil Nadu" },
    { city: "Bareilly", state: "Uttar Pradesh", display: "Bareilly, Uttar Pradesh" },
    { city: "Moradabad", state: "Uttar Pradesh", display: "Moradabad, Uttar Pradesh" },
    { city: "Mysuru", state: "Karnataka", display: "Mysuru, Karnataka" },
    { city: "Gurgaon", state: "Haryana", display: "Gurgaon, Haryana" },
    { city: "Aligarh", state: "Uttar Pradesh", display: "Aligarh, Uttar Pradesh" },
    { city: "Jalandhar", state: "Punjab", display: "Jalandhar, Punjab" },
    { city: "Bhubaneswar", state: "Odisha", display: "Bhubaneswar, Odisha" },
    { city: "Salem", state: "Tamil Nadu", display: "Salem, Tamil Nadu" },
    { city: "Warangal", state: "Telangana", display: "Warangal, Telangana" },
    { city: "Guntur", state: "Andhra Pradesh", display: "Guntur, Andhra Pradesh" },
    { city: "Bhiwandi", state: "Maharashtra", display: "Bhiwandi, Maharashtra" },
    { city: "Saharanpur", state: "Uttar Pradesh", display: "Saharanpur, Uttar Pradesh" },
    { city: "Gorakhpur", state: "Uttar Pradesh", display: "Gorakhpur, Uttar Pradesh" },
    { city: "Bikaner", state: "Rajasthan", display: "Bikaner, Rajasthan" },
    { city: "Amravati", state: "Maharashtra", display: "Amravati, Maharashtra" },
    { city: "Noida", state: "Uttar Pradesh", display: "Noida, Uttar Pradesh" },
    { city: "Jamshedpur", state: "Jharkhand", display: "Jamshedpur, Jharkhand" },
    { city: "Bhilai", state: "Chhattisgarh", display: "Bhilai, Chhattisgarh" },
    { city: "Cuttack", state: "Odisha", display: "Cuttack, Odisha" },
    { city: "Firozabad", state: "Uttar Pradesh", display: "Firozabad, Uttar Pradesh" },
    { city: "Kochi", state: "Kerala", display: "Kochi, Kerala" },
    { city: "Nellore", state: "Andhra Pradesh", display: "Nellore, Andhra Pradesh" },
    { city: "Bhavnagar", state: "Gujarat", display: "Bhavnagar, Gujarat" },
    { city: "Dehradun", state: "Uttarakhand", display: "Dehradun, Uttarakhand" },
    { city: "Durgapur", state: "West Bengal", display: "Durgapur, West Bengal" },
    { city: "Asansol", state: "West Bengal", display: "Asansol, West Bengal" },
    { city: "Rourkela", state: "Odisha", display: "Rourkela, Odisha" },
    { city: "Nanded", state: "Maharashtra", display: "Nanded, Maharashtra" },
    { city: "Kolhapur", state: "Maharashtra", display: "Kolhapur, Maharashtra" },
    { city: "Ajmer", state: "Rajasthan", display: "Ajmer, Rajasthan" },
    { city: "Akola", state: "Maharashtra", display: "Akola, Maharashtra" },
    { city: "Gulbarga", state: "Karnataka", display: "Gulbarga, Karnataka" },
    { city: "Jamnagar", state: "Gujarat", display: "Jamnagar, Gujarat" },
    { city: "Ujjain", state: "Madhya Pradesh", display: "Ujjain, Madhya Pradesh" },
    { city: "Loni", state: "Uttar Pradesh", display: "Loni, Uttar Pradesh" },
    { city: "Siliguri", state: "West Bengal", display: "Siliguri, West Bengal" },
    { city: "Jhansi", state: "Uttar Pradesh", display: "Jhansi, Uttar Pradesh" },
    { city: "Ulhasnagar", state: "Maharashtra", display: "Ulhasnagar, Maharashtra" },
    { city: "Jammu", state: "Jammu and Kashmir", display: "Jammu, Jammu and Kashmir" },
    { city: "Sangli-Miraj & Kupwad", state: "Maharashtra", display: "Sangli-Miraj & Kupwad, Maharashtra" },
    { city: "Mangalore", state: "Karnataka", display: "Mangalore, Karnataka" },
    { city: "Erode", state: "Tamil Nadu", display: "Erode, Tamil Nadu" },
    { city: "Belgaum", state: "Karnataka", display: "Belgaum, Karnataka" },
    { city: "Ambattur", state: "Tamil Nadu", display: "Ambattur, Tamil Nadu" },
    { city: "Tirunelveli", state: "Tamil Nadu", display: "Tirunelveli, Tamil Nadu" },
    { city: "Malegaon", state: "Maharashtra", display: "Malegaon, Maharashtra" },
    { city: "Gaya", state: "Bihar", display: "Gaya, Bihar" },
    { city: "Jalgaon", state: "Maharashtra", display: "Jalgaon, Maharashtra" },
    { city: "Udaipur", state: "Rajasthan", display: "Udaipur, Rajasthan" },
    { city: "Maheshtala", state: "West Bengal", display: "Maheshtala, West Bengal" },
];

export const HOARDING_TYPES = [
    "Hoarding",
    "Unipole",
    "Gantry",
    "Bus Shelter",
    "Kiosk",
    "Other"
];
